import '../styles/index.scss';
import {Personne} from "./modele/Personne.js";
let pers=new Personne(2548,"Mbengue","abdoulahi","783735236","abdoulahi7@outlook.fr");
import {Etudiant} from "./modele/Etudiant.js";
import {Departement} from "./modele/Departement.js";
import {College} from "./modele/College.js";
import {Cours} from "./modele/Cours";
import {Salle} from "./modele/Salle";
import {EtudiantNote} from "./modele/EtudiantNote.js";
import { Enseignant } from "./modele/Enseignant.js";
let dept=new Array();
let clg=new College(2510,"CEM Tacko","cemtacko@gmail.com",dept);
let ensei= new Array();
dept[0]= new Departement(2257,"LMIO",ensei,"Sylla",clg);
dept[1]=new Departement(661,"Economique et Gestion",ensei,"WADE",clg);
let crs=new Array();
crs[0]=new Cours(554,"Pc","salle 1","monsieur Mbaye");
crs[1]=new Cours(48,"svt","salle 2","toumbou");
console.log(crs[1]);
let note=new EtudiantNote("samba diakhite","dev web",19);
console.log(note);
console.log(pers);
console.log(dept[0]);
ensei[0]=new Enseignant(crs[0],dept[0],1995,783735236,"MBENGUE","Mame Maty",774174208,"abdoulahim71@gmail.com");
console.log(ensei[0]);
console.log(JSON.stringify(note));
console.log(crs[1]);